artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/uc?/export=download&id=1Rfn_h7aGCgpSAuZJVm2oGM31Rl6f2Xs3
  data_dir: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

base_model_preparation:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/base_model.h5
  updated_base_model_path: artifacts/base_model/updated_base_model.h5

model_trainer:
  root_dir: artifacts/model_trainer
  trained_model_path: artifacts/model_trainer/trained_model.h5
  train_data_path: artifacts/data_ingestion/Data/train
  valid_data_path: artifacts/data_ingestion/Data/valid
  test_data_path: artifacts/data_ingestion/Data/test
  train_history_dir: artifacts/model_trainer/model_history
  loss_images_path: artifacts/model_trainer/model_history/loss_image.png
  accuracy_images_path: artifacts/model_trainer/model_history/accuracy_image.png
  history_json_path: artifacts/model_trainer/model_history/model_history.json
